#!/bin/bash

sudo mkdir /usr/share/boot-video
sudo cp /opt/RetroPie_Rock5b/config/boot-video.mp4 /usr/share/boot-video/
sudo apt-get update -y
sudo apt-get install mpv -y

sudo tee /etc/init.d/boot-video.sh > /dev/null << EOF
/usr/bin/mpv --no-audio --no-osc --no-input-default-bindings --fs /usr/share/boot-video/boot-video.mp4 &
EOF

sudo chmod +x /etc/init.d/boot-video.sh
sudo update-rc.d boot-video.sh defaults

