#!/bin/bash
# B.Titze 2023      
      BLACK='\033[0;39m'
      BLUE='\033[1;34m'
      GREEN='\033[1;32m'
      RED='\033[1;31m'
      GREY='\033[1;30m'

mpv  --no-osc --no-input-default-bindings --fs /usr/share/boot-video/boot-video.mp4 > /dev/null 2>&1 &

clear
toilet "RockPi" --metal

wget -q --spider http://google.com

 if [ $? -eq 0 ]; then

#First install
if [ ! -d /etc/emulationstation/themes/magazinemadness/ ]; then


      sudo mkdir -p /etc/emulationstation/themes
      sudo chmod -R 777 /etc/emulationstation

      sudo chmod -R 777 /etc/emulationstation
      git clone --recursive --depth 1 --branch master "https://github.com/RetroHursty69/es-theme-magazinemadness.git" "/etc/emulationstation/themes/magazinemadness"
fi

if [ ! -d ~/RetroPie/BIOS/mame2003/ ]; then
    mkdir ~/RetroPie
    mkdir -p ~/RetroPie/BIOS

    sudo chmod -R 777 ~/RetroPie
    sudo apt install feh -y
    clear
    toilet "RockPi" --metal
    cd ~ 
    git clone --depth=1 https://github.com/archtaurus/RetroPieBIOS.git
    sudo cp -rf ~/RetroPieBIOS/BIOS/* ~/RetroPie/BIOS
    rm -rf ~/RetroPieBIOS 
fi

 if [ ! -f ~/RetroPie/roms/gba/gamelist.xml ]; then
      #Install Basic Roms from archive.org
      sudo chmod -R 777 ~/RetroPie
      cd /home/$USER/RetroPie
      wget https://archive.org/download/archive_20190819/Romset.zip
          
      cd ~/RetroPie/roms
      sudo unzip -o  /home/$USER/RetroPie/Romset.zip
      rm -rf /home/$USER/RetroPie/Romset.zip
      #BezelProject. https://www.youtube.com/watch?v=uq8IecVQ6yY
      cd /home/pi/RetroPie/retropiemenu/
      wget https://raw.githubusercontent.com/thebezelproject/BezelProject/master/bezelproject.sh
      chmod +x "bezelproject.sh"
      
      #Eazy-Hax-RetroPie-Toolkit
      curl https://raw.githubusercontent.com/Shakz76/Eazy-Hax-RetroPie-Toolkit/master/cfg/Install%20Eazy%20Hax%20RetroPie%20Toolkit.sh | bash
      
      fi
        sudo chmod -R 777 ~/RetroPie
        sudo chmod -R 777 ~/RetroPie-Setup
        sudo chmod -R 777 /opt/retropie
       sleep 10
        emulationstation
else
    whiptail --msgbox " First run, please connect to internet ..." 20 50 1
 
 fi
cd
toilet "RetroRock" --metal
      echo -e "$BLUE RetroRock ROM Operating System and Libraries" 
      echo -e "$GREY Version V2.0 2020-2021 RetroRock-OS "
echo " No Rights Reserved.  "
echo -e "$BLACK "
echo " Type 'd' start Workbench "
echo -e "$BLUE "
echo " 1.>  "
echo -e " 1.>  ( e ) Emulationstation                    "
echo -e " 1.>  ( d ) Linux Desktop                       "
echo -e " 1.>  ( r ) Retropie setup                      "
echo " 1.>  ( m ) Config Menu                            " 
echo " 1.>  ( u ) RetroRock update                       " 
echo " 1.>  ( s ) Shutdown                               "  
echo -e "$GREY "
cd
