#!/bin/bash
# B.Titze 2023

BLACK='\033[0;39m'
BLUE='\033[1;34m'
GREEN='\033[1;32m'
RED='\033[1;31m'
GREY='\033[1;30m'



 power
 
cd
clear
      toilet "RetroRock" --metal
      echo -e "$BLUE RetroRock-OS ROM Operating System and Libraries" 
      echo -e "$GREY Version V2.0 2020-2023 RetroRock-OS "
      echo " No Rights Reserved.  "
      echo " "
      echo -e "$GREY "

#************************* repair & Check dpkg **********************************************************************

       
sudo dpkg --configure -a
 clear
      toilet "RetroRock" --metal
      echo -e "$BLUE RetroRock-OS ROM Operating System and Libraries" 
      echo -e "$GREY Version V2.0 2020-2023 RetroRock-OS "
      echo " No Rights Reserved.  "
      echo " "
sudo apt -y --fix-broken install
 clear
      toilet "RetroRock" --metal
      echo -e "$BLUE RetroRock-OS ROM Operating System and Libraries" 
      echo -e "$GREY Version V2.0 2020-2023 RetroRock-OS "
      echo " No Rights Reserved.  "
      echo " "
sudo apt -f -y install
 clear
      toilet "RetroRock" --metal
      echo -e "$BLUE RetroRock-OS ROM Operating System and Libraries" 
      echo -e "$GREY Version V2.0 2020-2023 RetroRock-OS "
      echo " No Rights Reserved.  "
      echo " "
sudo apt-get autoremove -y
 clear
      toilet "RetroRock" --metal
      echo -e "$BLUE RetroRock-OS ROM Operating System and Libraries" 
      echo -e "$GREY Version V2.0 2020-2023 RetroRock-OS "
      echo " No Rights Reserved.  "
      echo " "
sudo apt-get autoclean
 clear
      toilet "RetroRock" --metal
      echo -e "$BLUE RetroRock-OS ROM Operating System and Libraries" 
      echo -e "$GREY Version V2.0 2020-2023 RetroRock-OS "
      echo " No Rights Reserved.  "
      echo " "
sudo apt-get clean -y
sudo apt-get update -y
sudo apt-get upgrade -y


#************************** Get update **********************************************************************

 clear
      toilet "RetroRock" --metal
      echo -e "$BLUE RetroRock-OS ROM Operating System and Libraries" 
      echo -e "$GREY Version V2.0 2020-2023 RetroRock-OS "
      echo " No Rights Reserved.  "
      echo " "


      sudo rm -rf ~/RetroPie_Rock5b/
      sudo rm -rf /opt/RetroPie_Rock5b/


      cd
      git clone --depth=1 https://github.com/Jodels2002/RetroPie_Rock5b.git
      
      sudo chmod -R 777 RetroPie_Rock5b
     
      
      sudo cp -f -R ~/RetroPie_Rock5b/scripts/* /usr/local/bin
      sudo cp -f -R ~/RetroPie_Rock5b/ /opt
      sudo chmod -R 777 /usr/local/bin
      sudo chmod -R 777 /opt/RetroPie_Rock5b/


      
      ~/RetroPie_Rock5b/scripts/retropie_rock5b.sh
 
